### ISSUE TITLE
Fatal Frame: Mask of the Lunar Eclipse support

### ISSUE THREAD

**Issue by joao-oli** [Timo654/No-More-RSL#2]
Hi, I'm trying to mod this game and I'm having some problems extracting the .rsl files, they are said to be compatible, but they turn into some incompatible format I can't open. Could you please take a look? Link to the files: https://drive.google.com/file/d/1eichoNWXtm1IfmdoCazi7dRtfeO4tH_J/view?usp=sharing

- The "HAYA, Hide, Miya" folders contain images and textures; 
- The "RSL" folder has more effects and images, map, objects and character models and its animation files:
(*the files with "EF" in the beginning stand for effects and other images; 
*the map models start with "R" and some numbers after, like "R163"; 
*the objects models start with "I" and some numbers after, like "I010"; 
*examples of a character model "RUK00" and its animation files: "RUKA00", "RUKA01".)

**Comment by Timo654** [comment]
I can't access the google drive link, could you please make it public?

**Comment by joao-oli** [comment]
Ok! Here is the new link: https://drive.google.com/file/d/1eichoNWXtm1IfmdoCazi7dRtfeO4tH_J/view?usp=sharing

**Comment by Timo654** [comment]
So, what's the issue exactly?
The files seem to unpack just fine and they don't appear to be corrupted.
![item6721_a binout](https://user-images.githubusercontent.com/41972888/151822285-48be2797-eeaf-4f13-8dbd-ba39f4957c10.png)
Here's a random texture I extracted from the files you sent.
What do you mean by incompatible format? This tool is only for unpacking .RSL containers, not for viewing textures or editing models/scripts/whatever. Repacking the files also seems to work, although I don't have the game so I couldn't test that.

**Comment by joao-oli** [comment]
I just couldn't open the files after extracting them, so I thought the files weren't compatible. What program did you use to open this texture? Also, the animation files extracted turned into a .GAN file which I couldn't find anything to open it. Repacking also can be only used with the file I extracted? Thanks for testing the texture, I was in doubt whether the files were incompatible or I was just doing some mistake haha

**Comment by Timo654** [comment]
There's a Noesis script for the model and texture files here: https://github.com/Zheneq/Noesis-Plugins
It doesn't support individual files though, only the entire rsl container.

I edited the texture script slightly to allow me to open a single texture instead of the entire rsl file.

**Comment by joao-oli** [comment]
I already have this script, it just doesn't support animation files, which I used your extractor to acquire them, but I don't know what to do with the .GAN files they turn into. I extracted one texture and an image and it gave me a bin file, which I tried to convert it to an jpeg/png and it didn't work out. How can I open these extracted files then? Also, to repack a file to .rsl, it needs to have the .json script? Is there any other way to convert any file to .rsl?

**Comment by Timo654** [comment]
I don't know how to open the animation files. bin is just a generic file extension, it could be anything. I don't mod Fatal Frame so I don't know what the files are exactly.

The json has metadata about the files, so yeah, it's needed. RSL files are containers, why do you want to convert a file to RSL?
But I guess you could make your own json and then it'd work.

Anyways, there's no issue with my tool so I'll close this.

**Comment by SimplyEarly** [comment]
Ok, thanks for answering anyway! I could send the .GAN extracted animation files if you want to take a look. I extracted no more heroes animation files and it resulted in G1M files, so I wanted to know why this game turned into a .GAN file. I wanted to convert a file to RSL to mod into the game.
[RSL animation file extracted.zip](https://github.com/Timo654/No-More-RSL/files/7973276/RSL.animation.file.extracted.zip)

**Comment by joao-oli** [comment]
Thanks for answering anyway! And sorry if I bothered you or anything, I really thought the game files were just incompatible with the tool xD. This is a great tool, keep up the good work!

**Comment by joao-oli** [comment]
> There's a Noesis script for the model and texture files here: https://github.com/Zheneq/Noesis-Plugins It doesn't support individual files though, only the entire rsl container.
> 
> I edited the texture script slightly to allow me to open a single texture instead of the entire rsl file.

Oh, now I understood what you meant. The RSL is just holding a bunch of other files, right? I understood it all wrong, I'm used to reading things fast and I didn't notice what you meant by "the RSL is a container". Sorry haha, could you please explain to me what did you edit in the texture script to only open a single file? Also, can I send the .GAN extracted animation files, in case you want to take a look? I extracted no more heroes animation files and it resulted in G1M files, so I wanted to know why this game turned into a .GAN file.
[RSL extracted animation files.zip](https://github.com/Timo654/No-More-RSL/files/7974394/RSL.extracted.animation.files.zip)
